name: Terraform Validate
on:
  push:
    paths:
      - "Terraform/*.tf"
      - "Terraform/*.tf.json"
    branches:
      - "!main"
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check for utility bucket
        run: aws s3 ls | grep ${{ secrets.UTILITY_BUCKET }}

      - name: Terraform Init
        working-directory: Terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: Terraform
        run: terraform plan \
          -var 'username=${{ secrets.PGUSER }}' \
          -var 'password=${{ secrets.PGPASSWORD }}' \
          -var 'port=${{ secrets.PGPORT }}' \
          -var 'host=${{ secrets.PGHOST }}' \
          -var 'database=${{ secrets.PGDATABASE }}'
